package com.hibernate.beans;

// Generated 2016-8-23 10:37:13 by Hibernate Tools 3.4.0.CR1

/**
 * Channel generated by hbm2java
 */
public class Channel implements java.io.Serializable {

	private Integer channelId;
	private String part1;
	private String part2;

	public Channel() {
	}

	public Channel(String part1, String part2) {
		this.part1 = part1;
		this.part2 = part2;
	}

	public Integer getChannelId() {
		return this.channelId;
	}

	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	public String getPart1() {
		return this.part1;
	}

	public void setPart1(String part1) {
		this.part1 = part1;
	}

	public String getPart2() {
		return this.part2;
	}

	public void setPart2(String part2) {
		this.part2 = part2;
	}

}
