package com.hibernate.beans;

// Generated 2016-9-6 20:38:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Coverofintermediateinspection generated by hbm2java
 */
public class Coverofintermediateinspection implements java.io.Serializable {

	private Integer coverOfIntermediateInspectionId;
	private String n1;
	private String n2;
	private String n3;
	private String n4;
	private String n5;
	private String n6;
	private String n7;
	private String n8;
	private Boolean isEdit;
	private Integer enterpriseProjectId;
	private Date date;
	private Integer state;
	private Integer governmentId;

	public Coverofintermediateinspection() {
	}

	public Coverofintermediateinspection(String n1, String n2, String n3,
			String n4, String n5, String n6, String n7, String n8,
			Boolean isEdit, Integer enterpriseProjectId, Date date,
			Integer state, Integer governmentId) {
		this.n1 = n1;
		this.n2 = n2;
		this.n3 = n3;
		this.n4 = n4;
		this.n5 = n5;
		this.n6 = n6;
		this.n7 = n7;
		this.n8 = n8;
		this.isEdit = isEdit;
		this.enterpriseProjectId = enterpriseProjectId;
		this.date = date;
		this.state = state;
		this.governmentId = governmentId;
	}

	public Integer getCoverOfIntermediateInspectionId() {
		return this.coverOfIntermediateInspectionId;
	}

	public void setCoverOfIntermediateInspectionId(
			Integer coverOfIntermediateInspectionId) {
		this.coverOfIntermediateInspectionId = coverOfIntermediateInspectionId;
	}

	public String getN1() {
		return this.n1;
	}

	public void setN1(String n1) {
		this.n1 = n1;
	}

	public String getN2() {
		return this.n2;
	}

	public void setN2(String n2) {
		this.n2 = n2;
	}

	public String getN3() {
		return this.n3;
	}

	public void setN3(String n3) {
		this.n3 = n3;
	}

	public String getN4() {
		return this.n4;
	}

	public void setN4(String n4) {
		this.n4 = n4;
	}

	public String getN5() {
		return this.n5;
	}

	public void setN5(String n5) {
		this.n5 = n5;
	}

	public String getN6() {
		return this.n6;
	}

	public void setN6(String n6) {
		this.n6 = n6;
	}

	public String getN7() {
		return this.n7;
	}

	public void setN7(String n7) {
		this.n7 = n7;
	}

	public String getN8() {
		return this.n8;
	}

	public void setN8(String n8) {
		this.n8 = n8;
	}

	public Boolean getIsEdit() {
		return this.isEdit;
	}

	public void setIsEdit(Boolean isEdit) {
		this.isEdit = isEdit;
	}

	public Integer getEnterpriseProjectId() {
		return this.enterpriseProjectId;
	}

	public void setEnterpriseProjectId(Integer enterpriseProjectId) {
		this.enterpriseProjectId = enterpriseProjectId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Integer getGovernmentId() {
		return this.governmentId;
	}

	public void setGovernmentId(Integer governmentId) {
		this.governmentId = governmentId;
	}

}
