package com.hibernate.beans;

// Generated 2016-8-22 10:31:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Enterprise generated by hbm2java
 */
public class Enterprise implements java.io.Serializable {

	private Integer enterpriseId;
	private String name;
	private String legalPerson;
	private String loginName;
	private String password;
	private Date registrationTime;
	private String registeredCapital;
	private String unit;
	private String channel1;
	private String channel2;
	private String contact;
	private String phone;
	private String email;
	private String postcode;
	private int roleId;

	public Enterprise() {
	}

	public Enterprise(int roleId) {
		this.roleId = roleId;
	}

	public Enterprise(String name, String legalPerson, String loginName,
			String password, Date registrationTime, String registeredCapital,
			String unit, String channel1, String channel2, String contact,
			String phone, String email, String postcode, int roleId) {
		this.name = name;
		this.legalPerson = legalPerson;
		this.loginName = loginName;
		this.password = password;
		this.registrationTime = registrationTime;
		this.registeredCapital = registeredCapital;
		this.unit = unit;
		this.channel1 = channel1;
		this.channel2 = channel2;
		this.contact = contact;
		this.phone = phone;
		this.email = email;
		this.postcode = postcode;
		this.roleId = roleId;
	}

	public Integer getEnterpriseId() {
		return this.enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLegalPerson() {
		return this.legalPerson;
	}

	public void setLegalPerson(String legalPerson) {
		this.legalPerson = legalPerson;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getRegistrationTime() {
		return this.registrationTime;
	}

	public void setRegistrationTime(Date registrationTime) {
		this.registrationTime = registrationTime;
	}

	public String getRegisteredCapital() {
		return this.registeredCapital;
	}

	public void setRegisteredCapital(String registeredCapital) {
		this.registeredCapital = registeredCapital;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getChannel1() {
		return this.channel1;
	}

	public void setChannel1(String channel1) {
		this.channel1 = channel1;
	}

	public String getChannel2() {
		return this.channel2;
	}

	public void setChannel2(String channel2) {
		this.channel2 = channel2;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

}
