package com.hibernate.beans;

// Generated 2016-8-21 18:32:50 by Hibernate Tools 3.4.0.CR1

/**
 * Expert generated by hbm2java
 */
public class Expert implements java.io.Serializable {

	private Integer expertId;
	private String name;
	private Integer age;
	private String company;
	private String title;
	private String major;
	private String education;
	private String cellphone;
	private String telephone;
	private String email;
	private String achievement;
	private String type;
	private String loginName;
	private String password;
	private int roleId;
	private String field1;
	private String field2;

	public Expert() {
	}

	public Expert(String loginName, String password, int roleId) {
		this.loginName = loginName;
		this.password = password;
		this.roleId = roleId;
	}

	public Expert(String name, Integer age, String company, String title,
			String major, String education, String cellphone, String telephone,
			String email, String achievement, String type, String loginName,
			String password, int roleId, String field1, String field2) {
		this.name = name;
		this.age = age;
		this.company = company;
		this.title = title;
		this.major = major;
		this.education = education;
		this.cellphone = cellphone;
		this.telephone = telephone;
		this.email = email;
		this.achievement = achievement;
		this.type = type;
		this.loginName = loginName;
		this.password = password;
		this.roleId = roleId;
		this.field1 = field1;
		this.field2 = field2;
	}

	public Integer getExpertId() {
		return this.expertId;
	}

	public void setExpertId(Integer expertId) {
		this.expertId = expertId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAchievement() {
		return this.achievement;
	}

	public void setAchievement(String achievement) {
		this.achievement = achievement;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getField1() {
		return this.field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

}
