package com.hibernate.beans;

// Generated 2016-8-23 9:45:42 by Hibernate Tools 3.4.0.CR1

/**
 * Field generated by hbm2java
 */
public class Field implements java.io.Serializable {

	private Integer fieldId;
	private String name;

	public Field() {
	}

	public Field(String name) {
		this.name = name;
	}

	public Integer getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(Integer fieldId) {
		this.fieldId = fieldId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
