package com.hibernate.beans;

// Generated 2016-9-6 20:38:39 by Hibernate Tools 3.4.0.CR1

/**
 * Intermediateinspectioninfo generated by hbm2java
 */
public class Intermediateinspectioninfo implements java.io.Serializable {

	private int coverOfIntermediateInspection;
	private String o1;
	private String o2;
	private String o3;
	private String o4;
	private String o5;
	private String o6;
	private String o7;
	private String o8;
	private String o9;
	private String o10;
	private String o11;
	private String o12;
	private String o13;
	private String o14;
	private String o15;
	private String o16;
	private String o17;
	private String o18;
	private String o19;
	private String o20;
	private String o21;
	private String o22;
	private String o23;
	private String o24;
	private String o25;
	private String o26;
	private String o27;
	private String o28;
	private String o29;
	private String o30;
	private String o31;
	private String o32;
	private String o33;
	private String o34;
	private String o35;
	private String o36;
	private String o37;
	private String o38;
	private String o39;
	private String o40;
	private String o41;
	private String o42;
	private String o43;
	private String o44;
	private String o45;
	private String o46;
	private String o47;
	private String o48;
	private String o49;

	public Intermediateinspectioninfo() {
	}

	public Intermediateinspectioninfo(int coverOfIntermediateInspection) {
		this.coverOfIntermediateInspection = coverOfIntermediateInspection;
	}

	public Intermediateinspectioninfo(int coverOfIntermediateInspection,
			String o1, String o2, String o3, String o4, String o5, String o6,
			String o7, String o8, String o9, String o10, String o11,
			String o12, String o13, String o14, String o15, String o16,
			String o17, String o18, String o19, String o20, String o21,
			String o22, String o23, String o24, String o25, String o26,
			String o27, String o28, String o29, String o30, String o31,
			String o32, String o33, String o34, String o35, String o36,
			String o37, String o38, String o39, String o40, String o41,
			String o42, String o43, String o44, String o45, String o46,
			String o47, String o48, String o49) {
		this.coverOfIntermediateInspection = coverOfIntermediateInspection;
		this.o1 = o1;
		this.o2 = o2;
		this.o3 = o3;
		this.o4 = o4;
		this.o5 = o5;
		this.o6 = o6;
		this.o7 = o7;
		this.o8 = o8;
		this.o9 = o9;
		this.o10 = o10;
		this.o11 = o11;
		this.o12 = o12;
		this.o13 = o13;
		this.o14 = o14;
		this.o15 = o15;
		this.o16 = o16;
		this.o17 = o17;
		this.o18 = o18;
		this.o19 = o19;
		this.o20 = o20;
		this.o21 = o21;
		this.o22 = o22;
		this.o23 = o23;
		this.o24 = o24;
		this.o25 = o25;
		this.o26 = o26;
		this.o27 = o27;
		this.o28 = o28;
		this.o29 = o29;
		this.o30 = o30;
		this.o31 = o31;
		this.o32 = o32;
		this.o33 = o33;
		this.o34 = o34;
		this.o35 = o35;
		this.o36 = o36;
		this.o37 = o37;
		this.o38 = o38;
		this.o39 = o39;
		this.o40 = o40;
		this.o41 = o41;
		this.o42 = o42;
		this.o43 = o43;
		this.o44 = o44;
		this.o45 = o45;
		this.o46 = o46;
		this.o47 = o47;
		this.o48 = o48;
		this.o49 = o49;
	}

	public int getCoverOfIntermediateInspection() {
		return this.coverOfIntermediateInspection;
	}

	public void setCoverOfIntermediateInspection(
			int coverOfIntermediateInspection) {
		this.coverOfIntermediateInspection = coverOfIntermediateInspection;
	}

	public String getO1() {
		return this.o1;
	}

	public void setO1(String o1) {
		this.o1 = o1;
	}

	public String getO2() {
		return this.o2;
	}

	public void setO2(String o2) {
		this.o2 = o2;
	}

	public String getO3() {
		return this.o3;
	}

	public void setO3(String o3) {
		this.o3 = o3;
	}

	public String getO4() {
		return this.o4;
	}

	public void setO4(String o4) {
		this.o4 = o4;
	}

	public String getO5() {
		return this.o5;
	}

	public void setO5(String o5) {
		this.o5 = o5;
	}

	public String getO6() {
		return this.o6;
	}

	public void setO6(String o6) {
		this.o6 = o6;
	}

	public String getO7() {
		return this.o7;
	}

	public void setO7(String o7) {
		this.o7 = o7;
	}

	public String getO8() {
		return this.o8;
	}

	public void setO8(String o8) {
		this.o8 = o8;
	}

	public String getO9() {
		return this.o9;
	}

	public void setO9(String o9) {
		this.o9 = o9;
	}

	public String getO10() {
		return this.o10;
	}

	public void setO10(String o10) {
		this.o10 = o10;
	}

	public String getO11() {
		return this.o11;
	}

	public void setO11(String o11) {
		this.o11 = o11;
	}

	public String getO12() {
		return this.o12;
	}

	public void setO12(String o12) {
		this.o12 = o12;
	}

	public String getO13() {
		return this.o13;
	}

	public void setO13(String o13) {
		this.o13 = o13;
	}

	public String getO14() {
		return this.o14;
	}

	public void setO14(String o14) {
		this.o14 = o14;
	}

	public String getO15() {
		return this.o15;
	}

	public void setO15(String o15) {
		this.o15 = o15;
	}

	public String getO16() {
		return this.o16;
	}

	public void setO16(String o16) {
		this.o16 = o16;
	}

	public String getO17() {
		return this.o17;
	}

	public void setO17(String o17) {
		this.o17 = o17;
	}

	public String getO18() {
		return this.o18;
	}

	public void setO18(String o18) {
		this.o18 = o18;
	}

	public String getO19() {
		return this.o19;
	}

	public void setO19(String o19) {
		this.o19 = o19;
	}

	public String getO20() {
		return this.o20;
	}

	public void setO20(String o20) {
		this.o20 = o20;
	}

	public String getO21() {
		return this.o21;
	}

	public void setO21(String o21) {
		this.o21 = o21;
	}

	public String getO22() {
		return this.o22;
	}

	public void setO22(String o22) {
		this.o22 = o22;
	}

	public String getO23() {
		return this.o23;
	}

	public void setO23(String o23) {
		this.o23 = o23;
	}

	public String getO24() {
		return this.o24;
	}

	public void setO24(String o24) {
		this.o24 = o24;
	}

	public String getO25() {
		return this.o25;
	}

	public void setO25(String o25) {
		this.o25 = o25;
	}

	public String getO26() {
		return this.o26;
	}

	public void setO26(String o26) {
		this.o26 = o26;
	}

	public String getO27() {
		return this.o27;
	}

	public void setO27(String o27) {
		this.o27 = o27;
	}

	public String getO28() {
		return this.o28;
	}

	public void setO28(String o28) {
		this.o28 = o28;
	}

	public String getO29() {
		return this.o29;
	}

	public void setO29(String o29) {
		this.o29 = o29;
	}

	public String getO30() {
		return this.o30;
	}

	public void setO30(String o30) {
		this.o30 = o30;
	}

	public String getO31() {
		return this.o31;
	}

	public void setO31(String o31) {
		this.o31 = o31;
	}

	public String getO32() {
		return this.o32;
	}

	public void setO32(String o32) {
		this.o32 = o32;
	}

	public String getO33() {
		return this.o33;
	}

	public void setO33(String o33) {
		this.o33 = o33;
	}

	public String getO34() {
		return this.o34;
	}

	public void setO34(String o34) {
		this.o34 = o34;
	}

	public String getO35() {
		return this.o35;
	}

	public void setO35(String o35) {
		this.o35 = o35;
	}

	public String getO36() {
		return this.o36;
	}

	public void setO36(String o36) {
		this.o36 = o36;
	}

	public String getO37() {
		return this.o37;
	}

	public void setO37(String o37) {
		this.o37 = o37;
	}

	public String getO38() {
		return this.o38;
	}

	public void setO38(String o38) {
		this.o38 = o38;
	}

	public String getO39() {
		return this.o39;
	}

	public void setO39(String o39) {
		this.o39 = o39;
	}

	public String getO40() {
		return this.o40;
	}

	public void setO40(String o40) {
		this.o40 = o40;
	}

	public String getO41() {
		return this.o41;
	}

	public void setO41(String o41) {
		this.o41 = o41;
	}

	public String getO42() {
		return this.o42;
	}

	public void setO42(String o42) {
		this.o42 = o42;
	}

	public String getO43() {
		return this.o43;
	}

	public void setO43(String o43) {
		this.o43 = o43;
	}

	public String getO44() {
		return this.o44;
	}

	public void setO44(String o44) {
		this.o44 = o44;
	}

	public String getO45() {
		return this.o45;
	}

	public void setO45(String o45) {
		this.o45 = o45;
	}

	public String getO46() {
		return this.o46;
	}

	public void setO46(String o46) {
		this.o46 = o46;
	}

	public String getO47() {
		return this.o47;
	}

	public void setO47(String o47) {
		this.o47 = o47;
	}

	public String getO48() {
		return this.o48;
	}

	public void setO48(String o48) {
		this.o48 = o48;
	}

	public String getO49() {
		return this.o49;
	}

	public void setO49(String o49) {
		this.o49 = o49;
	}

}
