package com.hibernate.beans;

// Generated 2016-8-29 15:51:15 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Makerproject generated by hbm2java
 */
public class Makerproject implements java.io.Serializable {

	private Integer makerProjectId;
	private String title;
	private Date startTime;
	private Date endTime;
	private String description;
	private byte[] fujian;
	private String fujianName;
	private String fujianType;

	public Makerproject() {
	}

	public Makerproject(String title, Date startTime, Date endTime,
			String description, byte[] fujian, String fujianName,
			String fujianType) {
		this.title = title;
		this.startTime = startTime;
		this.endTime = endTime;
		this.description = description;
		this.fujian = fujian;
		this.fujianName = fujianName;
		this.fujianType = fujianType;
	}

	public Integer getMakerProjectId() {
		return this.makerProjectId;
	}

	public void setMakerProjectId(Integer makerProjectId) {
		this.makerProjectId = makerProjectId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte[] getFujian() {
		return this.fujian;
	}

	public void setFujian(byte[] fujian) {
		this.fujian = fujian;
	}

	public String getFujianName() {
		return this.fujianName;
	}

	public void setFujianName(String fujianName) {
		this.fujianName = fujianName;
	}

	public String getFujianType() {
		return this.fujianType;
	}

	public void setFujianType(String fujianType) {
		this.fujianType = fujianType;
	}

}
