package com.base.hibernate.beans;

// Generated 2016-9-6 20:39:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Datagrid generated by hbm2java
 */
public class Datagrid implements java.io.Serializable {

	private String code;
	private String content;
	private String area;
	private Date date;

	public Datagrid() {
	}

	public Datagrid(String code) {
		this.code = code;
	}

	public Datagrid(String code, String content, String area, Date date) {
		this.code = code;
		this.content = content;
		this.area = area;
		this.date = date;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
