package com.base.hibernate.beans;

// Generated 2016-8-17 20:54:14 by Hibernate Tools 3.4.0.CR1

/**
 * Enum generated by hbm2java
 */
public class Enum implements java.io.Serializable {

	private int id;
	private String enum_;
	private String txt;

	public Enum() {
	}

	public Enum(int id, String enum_) {
		this.id = id;
		this.enum_ = enum_;
	}

	public Enum(int id, String enum_, String txt) {
		this.id = id;
		this.enum_ = enum_;
		this.txt = txt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getEnum_() {
		return this.enum_;
	}

	public void setEnum_(String enum_) {
		this.enum_ = enum_;
	}

	public String getTxt() {
		return this.txt;
	}

	public void setTxt(String txt) {
		this.txt = txt;
	}

}
