package com.base.hibernate.beans;

// Generated 2016-8-16 16:47:25 by Hibernate Tools 3.4.0.CR1

/**
 * Fujian generated by hbm2java
 */
public class Fujian implements java.io.Serializable {

	private Integer id;
	private byte[] fuJian;

	public Fujian() {
	}

	public Fujian(byte[] fuJian) {
		this.fuJian = fuJian;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public byte[] getFuJian() {
		return this.fuJian;
	}

	public void setFuJian(byte[] fuJian) {
		this.fuJian = fuJian;
	}

}
